## Vectors in Python

In [1]:
import numpy as np

#Vector-A
A = np.array([1, 2, 3])

#Vector-B
B = np.array([4, 5, 6])

In [2]:
C = A + B
print(C)

[5 7 9]


In [3]:
D = A - B
print(D)

[-3 -3 -3]


### (Element-wise product - Hadamard product)

In [4]:
E = A * B
print(E)

[ 4 10 18]


## Dot product

In [5]:
print(A.dot(B))

32


In [6]:
print(np.cross(A, B))

[-3  6 -3]


In [7]:
print(3 * A)

[3 6 9]


In [8]:
print(0.5 * A)

[0.5 1.  1.5]
