In [3]:
import numpy as np
arr1 = np.linspace(0, 10, 100)
arr1.shape

(100,)

In [6]:
arr2 = np.arange(1, 10).reshape(3,3)
arr3 = np.arange(11, 20).reshape(3,3)
print(arr2)
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [8]:
arr4 = np.vstack((arr2, arr3))
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [13]:
arr4[4]

array([14, 15, 16])