## General Torch Review

In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
float(a[1])

1.0

In [3]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.5]])
points

tensor([[4.0000, 1.0000],
        [5.0000, 3.0000],
        [2.0000, 1.5000]])

In [4]:
some_list = list(range(6))
print(some_list[:])  # Full list
print(some_list[1:4])  # 1 inclusive 4th not
print(some_list[1:])  # 1 to end
print(some_list[:4])  # start to 4 exclusive
print(some_list[:-1])  # start to 1 before last

[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]


In [5]:
img_t = torch.randn(3, 5, 5)     # [shape, rows, cols]
weights = torch.tensor([0.21, 0.71, 0.35])
batch_t = torch.randn(2, 3, 5, 5)     # [batch, shape, rows, cols]

In [6]:
print(img_t)
print(weights)
print(batch_t)

tensor([[[-0.6863,  0.1629,  1.5992, -0.2687, -1.2694],
         [ 0.7502, -0.2016, -0.2648,  0.0925, -1.4965],
         [-0.8090, -0.0617, -1.6143,  0.4611,  0.1372],
         [ 3.3752,  2.5224, -0.6460,  1.1853, -0.7863],
         [ 1.2148,  0.1048,  0.1740, -0.6992, -0.7198]],

        [[-0.4475, -0.4668, -1.0433,  0.4088, -1.0118],
         [ 1.1086,  0.5504,  0.1554, -1.8947,  0.1848],
         [-1.5241,  1.3003,  1.9049, -1.5025, -0.5467],
         [ 0.9516, -1.7565,  1.7750,  0.1349, -0.5086],
         [-1.1571, -0.1846, -1.0427, -0.0501, -1.8665]],

        [[-0.3682, -0.8063,  0.5526, -0.5343, -0.6837],
         [-0.9102,  0.9337, -0.5030, -0.4055,  0.2267],
         [ 0.0152,  0.6779, -0.1600, -0.8735,  1.0210],
         [ 0.2225, -0.2934, -0.3467, -0.6375,  0.1672],
         [-0.3314,  0.6737, -1.0039,  0.6806, -0.9571]]])
tensor([0.2100, 0.7100, 0.3500])
tensor([[[[-1.1593e+00,  7.5770e-01,  3.8997e-01, -8.3386e-01, -4.8346e-01],
          [-7.5214e-01, -2.5138e-01, -9.1842

In [7]:
img_gray = img_t.mean(-3)
batch_gray = batch_t.mean(-3)
img_gray.shape, batch_gray.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))