## General Torch Review

In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [2]:
a[1]

tensor(1.)

In [3]:
float(a[1])

1.0

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.5]])
points

tensor([[4.0000, 1.0000],
        [5.0000, 3.0000],
        [2.0000, 1.5000]])

In [ ]:
some_list = list(range(6))
print(some_list[:])  # Full list
print(some_list[1:4])  # 1 inclusive 4th not
print(some_list[1:])  # 1 to end
print(some_list[:4])  # start to 4 exclusive
print(some_list[:-1])  # start to 1 before last