In [1]:
import numpy as np
print(np.__version__)

1.21.4


In [2]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [3]:
np.random.randint(0, 10, (3, 3))

array([[6, 5, 3],
       [2, 8, 2],
       [7, 8, 4]])

In [4]:
x = np.arange(10)

In [5]:
x[:5]

array([0, 1, 2, 3, 4])

In [11]:
grid1 = np.arange(1, 10).reshape((3, 3))
grid1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1 = np.arange(16).reshape(4, 4)

In [17]:
arr2, arr3 = np.split(arr1, [2])

In [18]:
arr2, arr3

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))