In [ ]:
import torch
from torch.nn.utils.rnn import pad_sequence

# Define the list of sequences
sequences = [ [1, 2, 3], [4, 5], [6, 7, 8, 9] ]

# Define the max length of the sequences
max_length = 4

# Pad the sequences to the max_length
padded_sequences = pad_sequence(sequences, batch_first=True, padding_value=0, max_length=max_length)

# Convert the padded sequences to a tensor
sequences_tensor = torch.tensor(padded_sequences)

# Print the shape of the tensor
print(sequences_tensor.shape)


In [2]:
import tensorflow as tf



c:\Python310\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "


[[1], [2, 3], [4, 5, 6]]


In [4]:
sequence = [[1], [2, 3], [4, 5, 6]]
sequence = tf.keras.preprocessing.sequence.pad_sequences(sequence)
print(sequence)

[[0 0 1]
 [0 2 3]
 [4 5 6]]


In [ ]:
from torch.nn import CrossEntropyLoss

# Prepare the input
input_ids = torch.tensor(input_ids)
attention_masks = torch.tensor(attention_masks)

# Load the pre-trained model
model = GPT2LMHeadModel.from_pretrained('gpt2')

# Define the loss function
criterion = CrossEntropyLoss()

# Fine-tune the model on the dataset
model.train()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

for _ in range(num_epochs):
    # Forward pass
    output = model(input_ids, attention_mask=attention_masks)
    # Compute the loss
    loss = criterion(output.logits.view(-1, output.logits.size(-1)), input_ids.view(-1))
    # Backward pass and optimization
    loss.backward()
    optimizer.step()
